# Importando dados

In [2]:
import pandas as pd

In [15]:
dados_2010_01 = pd.read_csv('.\Dados\emprestimos-20101.csv')
dados_2010_02 = pd.read_csv('.\Dados\emprestimos-20102.csv')
dados_2011_01 = pd.read_csv('.\Dados\emprestimos-20111.csv')
dados_2011_02 = pd.read_csv('.\Dados\emprestimos-20112.csv')
dados_2012_01 = pd.read_csv('.\Dados\emprestimos-20121.csv')
dados_2012_02 = pd.read_csv('.\Dados\emprestimos-20122.csv')
dados_2013_01 = pd.read_csv('.\Dados\emprestimos-20131.csv')
dados_2013_02 = pd.read_csv('.\Dados\emprestimos-20132.csv')
dados_2014_01 = pd.read_csv('.\Dados\emprestimos-20141.csv')
dados_2014_02 = pd.read_csv('.\Dados\emprestimos-20142.csv')
dados_2015_01 = pd.read_csv('.\Dados\emprestimos-20151.csv')
dados_2015_02 = pd.read_csv('.\Dados\emprestimos-20152.csv')
dados_2016_01 = pd.read_csv('.\Dados\emprestimos-20161.csv')
dados_2016_02 = pd.read_csv('.\Dados\emprestimos-20162.csv')
dados_2017_01 = pd.read_csv('.\Dados\emprestimos-20171.csv')
dados_2017_02 = pd.read_csv('.\Dados\emprestimos-20172.csv')
dados_2018_01 = pd.read_csv('.\Dados\emprestimos-20181.csv')
dados_2018_02 = pd.read_csv('.\Dados\emprestimos-20182.csv')
dados_2019_01 = pd.read_csv('.\Dados\emprestimos-20191.csv')
dados_2019_02 = pd.read_csv('.\Dados\emprestimos-20192.csv')
dados_2020_01 = pd.read_csv('.\Dados\emprestimos-20201.csv')
dados_exemplares = pd.read_parquet('.\Dados\dados_exemplares.parquet')

# Concatenando os dados em um DataFrame

In [17]:
emprestimos = pd.concat(objs=[dados_2010_01, dados_2010_02, 
                              dados_2011_01, dados_2011_02, dados_2012_01, dados_2012_02, dados_2013_01, 
                              dados_2013_02, dados_2014_01, dados_2014_02, dados_2015_01, dados_2015_02, 
                              dados_2016_01, dados_2016_02, dados_2017_01, dados_2017_02, dados_2018_01, 
                              dados_2018_02, dados_2019_01, dados_2019_02, dados_2020_01])
emprestimos

,id_emprestimo,codigo_barras,data_renovacao,data_emprestimo,data_devolucao,matricula_ou_siape,tipo_vinculo_usuario
0,709684,L095049,NaN,2010/01/04 07:44:10.721000000,2010/01/05 16:26:12.662000000,2.008023e+09,ALUNO DE GRADUAÇÃO
1,709685,L167050,NaN,2010/01/04 07:44:10.750000000,2010/01/12 07:34:13.934000000,2.008023e+09,ALUNO DE GRADUAÇÃO
2,709686,2006017618,2010/01/26 08:07:01.738000000,2010/01/04 08:08:44.081000000,2010/02/25 07:36:25.800000000,2.008112e+09,ALUNO DE PÓS-GRADUAÇÃO
3,709687,L184117,2010/01/18 11:07:46.470000000,2010/01/04 08:24:21.284000000,2010/02/03 08:58:45.692000000,2.007211e+08,ALUNO DE GRADUAÇÃO
4,709684,L095049,NaN,2010/01/04 07:44:10.721000000,2010/01/05 16:26:12.662000000,2.008023e+09,ALUNO DE GRADUAÇÃO
...,...,...,...,...,...,...,...
26556,2989086,2008047044,NaN,2020/05/05 19:51:06.059000000,2021/05/13 14:53:31.000000000,3.067431e+06,SERVIDOR TÉCNICO-ADMINISTRATIVO
26557,2989087,2008047047,NaN,2020/05/05 19:51:06.135000000,2021/05/13 14:53:38.000000000,3.067431e+06,SERVIDOR TÉCNICO-ADMINISTRATIVO
26558,2989088,2010052905,NaN,2020/05/05 19:51:06.164000000,2021/05/13 15:01:46.000000000,3.067431e+06,SERVIDOR TÉCNICO-ADMINISTRATIVO
26559,2989089,2010048023,NaN,2020/06/09 11:54:02.669000000,2021/07/21 15:33:55.000000000,2.020101e+10,ALUNO DE PÓS-GRADUAÇÃO
26560,2989090,2013106838,NaN,2020/06/09 11:54:02.852000000,2021/07/21 15:33:45.000000000,2.020101e+10,ALUNO DE PÓS-GRADUAÇÃO

## Mesclando os dados da tabela de empréstimo com a tabela de exemplares

In [44]:
emprestimo_com_exemplares = pd.merge(emprestimos, dados_exemplares, how='left', on=None)
emprestimo_com_exemplares.head(10)

,id_emprestimo,codigo_barras,data_renovacao,data_emprestimo,data_devolucao,matricula_ou_siape,tipo_vinculo_usuario,id_exemplar,colecao,biblioteca,status_material,localizacao,registro_sistema
0,709684,L095049,NaN,2010/01/04 07:44:10.721000000,2010/01/05 16:26:12.662000000,2.008023e+09,ALUNO DE GRADUAÇÃO,13259.0,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,630.0,4225.0
1,709685,L167050,NaN,2010/01/04 07:44:10.750000000,2010/01/12 07:34:13.934000000,2.008023e+09,ALUNO DE GRADUAÇÃO,70865.0,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,647.0,25009.0
2,709686,2006017618,2010/01/26 08:07:01.738000000,2010/01/04 08:08:44.081000000,2010/02/25 07:36:25.800000000,2.008112e+09,ALUNO DE PÓS-GRADUAÇÃO,195347.0,Acervo Circulante,Biblioteca Setorial Prof. Rodolfo Helinski - E...,REGULAR,640.0,75019.0
3,709687,L184117,2010/01/18 11:07:46.470000000,2010/01/04 08:24:21.284000000,2010/02/03 08:58:45.692000000,2.007211e+08,ALUNO DE GRADUAÇÃO,131639.0,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,609.0,44494.0
4,709684,L095049,NaN,2010/01/04 07:44:10.721000000,2010/01/05 16:26:12.662000000,2.008023e+09,ALUNO DE GRADUAÇÃO,13259.0,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,630.0,4225.0
5,709685,L167050,NaN,2010/01/04 07:44:10.750000000,2010/01/12 07:34:13.934000000,2.008023e+09,ALUNO DE GRADUAÇÃO,70865.0,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,647.0,25009.0
6,709686,2006017618,2010/01/26 08:07:01.738000000,2010/01/04 08:08:44.081000000,2010/02/25 07:36:25.800000000,2.008112e+09,ALUNO DE PÓS-GRADUAÇÃO,195347.0,Acervo Circulante,Biblioteca Setorial Prof. Rodolfo Helinski - E...,REGULAR,640.0,75019.0
7,709687,L184117,2010/01/18 11:07:46.470000000,2010/01/04 08:24:21.284000000,2010/02/03 08:58:45.692000000,2.007211e+08,ALUNO DE GRADUAÇÃO,131639.0,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,609.0,44494.0
8,709688,2007027500,2010/01/19 15:59:26.464000000,2010/01/04 08:27:33.569000000,2010/02/03 13:06:30.662000000,2.009046e+09,ALUNO DE GRADUAÇÃO,225646.0,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,686.0,91736.0
9,709689,L157395,2010/01/19 15:59:26.447000000,2010/01/04 08:27:33.596000000,2010/02/03 13:06:43.125000000,2.009046e+09,ALUNO DE GRADUAÇÃO,57040.0,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,698.0,20943.0

# Limpeza de dados

In [40]:
emprestimo_com_exemplares.duplicated()

0          False
1          False
2          False
3          False
4           True
           ...
2261811    False
2261812    False
2261813    False
2261814    False
2261815    False
Length: 2261816, dtype: bool

In [42]:
emprestimo_com_exemplares.drop_duplicates(inplace=True)

In [ ]:
emprestimo_com_exemplares.reset_index(inplace=True)

In [50]:
emprestimo_com_exemplares.head(20)

,level_0,index,id_emprestimo,codigo_barras,data_renovacao,data_emprestimo,data_devolucao,matricula_ou_siape,tipo_vinculo_usuario,id_exemplar,colecao,biblioteca,status_material,localizacao,registro_sistema
0,0,0,709684,L095049,NaN,2010/01/04 07:44:10.721000000,2010/01/05 16:26:12.662000000,2.008023e+09,ALUNO DE GRADUAÇÃO,13259.0,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,630.0,4225.0
1,1,1,709685,L167050,NaN,2010/01/04 07:44:10.750000000,2010/01/12 07:34:13.934000000,2.008023e+09,ALUNO DE GRADUAÇÃO,70865.0,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,647.0,25009.0
2,2,2,709686,2006017618,2010/01/26 08:07:01.738000000,2010/01/04 08:08:44.081000000,2010/02/25 07:36:25.800000000,2.008112e+09,ALUNO DE PÓS-GRADUAÇÃO,195347.0,Acervo Circulante,Biblioteca Setorial Prof. Rodolfo Helinski - E...,REGULAR,640.0,75019.0
3,3,3,709687,L184117,2010/01/18 11:07:46.470000000,2010/01/04 08:24:21.284000000,2010/02/03 08:58:45.692000000,2.007211e+08,ALUNO DE GRADUAÇÃO,131639.0,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,609.0,44494.0
4,4,4,709684,L095049,NaN,2010/01/04 07:44:10.721000000,2010/01/05 16:26:12.662000000,2.008023e+09,ALUNO DE GRADUAÇÃO,13259.0,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,630.0,4225.0
5,5,5,709685,L167050,NaN,2010/01/04 07:44:10.750000000,2010/01/12 07:34:13.934000000,2.008023e+09,ALUNO DE GRADUAÇÃO,70865.0,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,647.0,25009.0
6,6,6,709686,2006017618,2010/01/26 08:07:01.738000000,2010/01/04 08:08:44.081000000,2010/02/25 07:36:25.800000000,2.008112e+09,ALUNO DE PÓS-GRADUAÇÃO,195347.0,Acervo Circulante,Biblioteca Setorial Prof. Rodolfo Helinski - E...,REGULAR,640.0,75019.0
7,7,7,709687,L184117,2010/01/18 11:07:46.470000000,2010/01/04 08:24:21.284000000,2010/02/03 08:58:45.692000000,2.007211e+08,ALUNO DE GRADUAÇÃO,131639.0,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,609.0,44494.0
8,8,8,709688,2007027500,2010/01/19 15:59:26.464000000,2010/01/04 08:27:33.569000000,2010/02/03 13:06:30.662000000,2.009046e+09,ALUNO DE GRADUAÇÃO,225646.0,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,686.0,91736.0
9,9,9,709689,L157395,2010/01/19 15:59:26.447000000,2010/01/04 08:27:33.596000000,2010/02/03 13:06:43.125000000,2.009046e+09,ALUNO DE GRADUAÇÃO,57040.0,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,698.0,20943.0
10,10,10,709690,2007019312,NaN,2010/01/04 08:49:57.857000000,2010/01/13 09:58:25.443000000,2.007014e+08,ALUNO DE GRADUAÇÃO,225786.0,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,698.0,91962.0
11,11,11,709691,2008046357,2010/01/19 11:50:13.404000000,2010/01/04 09:02:30.576000000,2010/02/02 12:13:36.132000000,2.005075e+08,ALUNO DE GRADUAÇÃO,256537.0,Acervo Circulante,Biblioteca Setorial Bertha Cruz Enders - ­Esco...,REGULAR,645.0,110273.0
12,12,12,709692,L187962,NaN,2010/01/04 09:07:06.131000000,2010/06/22 18:55:04.000000000,2.004044e+08,ALUNO DE GRADUAÇÃO,143654.0,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,658.0,51005.0
13,13,13,709693,L192776,NaN,2010/01/04 09:07:06.159000000,2010/06/22 18:54:46.000000000,2.004044e+08,ALUNO DE GRADUAÇÃO,159348.0,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,697.0,59235.0
14,14,14,709694,L202783,NaN,2010/01/04 09:09:38.329000000,2010/02/03 13:00:49.746000000,1.984206e+08,DOCENTE,274136.0,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,643.0,120537.0
15,15,15,709695,2007035128,NaN,2010/01/04 09:14:55.681000000,2010/01/14 10:15:08.388000000,2.008005e+09,ALUNO DE GRADUAÇÃO,235887.0,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,630.0,97666.0
16,16,16,709696,L122346,NaN,2010/01/04 09:14:55.721000000,2010/01/14 10:15:16.041000000,2.008005e+09,ALUNO DE GRADUAÇÃO,28681.0,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,612.0,10128.0
17,17,17,709697,L048797,NaN,2010/01/04 09:18:17.514000000,2010/01/14 10:14:59.964000000,2.008005e+09,ALUNO DE GRADUAÇÃO,131863.0,Acervo Circulante,Biblioteca Central Zila Mamede,REGULAR,673.0,44568.0
18,18,18,709698,2009047725,2010/01/18 14:44:41.163000000,2010/01/04 09:21:19.099000000,2010/02/02 12:02:38.444000000,2.009047e+09,ALUNO DE GRADUAÇÃO,281004.0,Acervo Circulante,Biblioteca Setorial do Centro Ciências da Saúd...,REGULAR,651.0,123552.0
19,19,19,709698,2009047725,2010/01/18 14:44:41.163000000,2010/01/04 09:21:19.099000000,2010/02/02 12:02:38.444000000,2.009047e+09,ALUNO DE GRADUAÇÃO,281004.0,Acervo Circulante,Biblioteca Setorial do Centro Ciências da Saúd...,REGULAR,651.0,123552.0